### ISSUE TITLE
App crashes when closing a popup that contains an indicator view (iOS only)

### ISSUE THREAD

**Issue by bluetreee** [LuckyDucko/Mopups#42]
As described in the title, when closing a popup that contains an indicator view, the app is crashing in iOS.  I have included a sample project and stacktrace to display the issue.  Can you take a look at it please?  Thank you.

For reference, I am using Visual Studio 17.4.4 with .NET SDK 7.0.102.

[CarouselPopupSample.zip](https://github.com/LuckyDucko/Mopups/files/10404833/CarouselPopupSample.zip)

```
**System.InvalidOperationException:** 'PlatformView cannot be null here'

2023-01-12 11:13:41.450630-0700 CarouselPopupSample[2799:1687340] 
Unhandled Exception:
System.InvalidOperationException: PlatformView cannot be null here
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IIndicatorView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiPageControl, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_PlatformView()
   at Microsoft.Maui.Handlers.IndicatorViewHandler.DisconnectHandler(MauiPageControl platformView)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IIndicatorView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiPageControl, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnDisconnectHandler(UIView platformView)
   at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
   at Microsoft.Maui.
Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
   at Mopups.iOS.Implementation.iOSMopups.DisposeModelAndChildrenHandlers(VisualElement view)
   at Mopups.iOS.Implementation.iOSMopups.RemoveAsync(PopupPage page)
   at Mopups.Services.PopupNavigation.<>c__DisplayClass23_0.<<RemovePageAsync>g__RemovePage|0>d.MoveNext()
--- End of stack trace from previous location ---
   at CarouselPopupSample.Popup.<>c.<<CloseButtonClicked>b__1_0>d.MoveNext() in C:\Users\aaoki\source\repos\CarouselPopupSample\Popup.xaml.cs:line 16
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at CarouselPopupSample.Program.Main(String[] args) in C:\Users\aaoki\source\repos\CarouselPopupSample\Platforms\iOS\Program.cs:line 13
2023-01-12 11:13:41.454885-0700 CarouselPopupSample[2799:1687340] Unhandled managed exception: PlatformView cannot be null here (System.InvalidOperationException)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IIndicatorView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiPageControl, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_PlatformView()
   at Microsoft.Maui.Handlers.IndicatorViewHandler.DisconnectHandler(MauiPageControl platformView)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IIndicatorView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiPageControl, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnDisconnectHandler(UIView platformView)
   at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
   at Microso
ft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
   at Mopups.iOS.Implementation.iOSMopups.DisposeModelAndChildrenHandlers(VisualElement view)
   at Mopups.iOS.Implementation.iOSMopups.RemoveAsync(PopupPage page)
   at Mopups.Services.PopupNavigation.<>c__DisplayClass23_0.<<RemovePageAsync>g__RemovePage|0>d.MoveNext()
--- End of stack trace from previous location ---
   at CarouselPopupSample.Popup.<>c.<<CloseButtonClicked>b__1_0>d.MoveNext() in C:\Users\aaoki\source\repos\CarouselPopupSample\Popup.xaml.cs:line 16
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at CarouselPopupSample.Program.Main(String[] args) in C:\Users\aaoki\source\repos\CarouselPopupSample\Platforms\iOS\Program.cs:line 13
```

**Comment by LuckyDucko** [comment]
Cheers for the example app, always makes these alot easier

This shouldn't be a difficult fix, looking at the stack trace, I'll get cracking on it asap.

**Comment by LennoxP90** [comment]
+1

**Comment by bluetreee** [comment]
Hi @LuckyDucko, do you have any updates for this bug or an estimated timeline for a fix?  Thanks!

**Comment by LuckyDucko** [comment]
@bluetreee my bad I have been completely zoned out regarding this plugin due to some other things going on. I'll refocus in this coming week

**Comment by LuckyDucko** [comment]
@bluetreee 

i don't want to sound like i'm shirking this responsibility, but this builds and works completely fine on my macbook through Visual Studio for mac.

**Comment by bluetreee** [comment]
@LuckyDucko I updated the my maui-ios workloads to 7.0.59 and it seems to be resolved now.  Thank you for looking into this!

**Comment by LuckyDucko** [comment]
No worries mate, have a good one
