### ISSUE TITLE
System.PlatformNotSupportedException is thrown when showing the popup in iOS

### ISSUE THREAD

**Issue by jsramraj** [LuckyDucko/Mopups#56]
I tried to show the popup in my iPad 16.1 Simulator and the app crashes with the following message

`Unhandled Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Temp.Program.Main(String[] args) in /Users/rthanga1/Official/Samples/temp/Temp/Temp/Platforms/iOS/Program.cs:line 13
`

**Comment by jsramraj** [comment]
[Temp.zip](https://github.com/LuckyDucko/Mopups/files/11048393/Temp.zip)

I have attached a sample project that raises this exception.

**Comment by bsloehr** [comment]
I am seeing the same issue but not on a simulator. When I deploy a Debug build to my iPad everything works properly. It is the same if I deploy a Release build, too but only if I compile and release from VS 2022 on Windows through my Macbook onto the iPad. If I deploy through Azure Devops then I get this same exception. @jsramraj  did you ever get a solution to this?

**Comment by LuckyDucko** [comment]
Oh this might be regarding issues with simulator builds in a different issue.

Could you download the repo and use it as a shared project instead of having it through nuget.

Once you have done that, can you play around with it a bit see what exception is thrown?

**Comment by bsloehr** [comment]
> Oh this might be regarding issues with simulator builds in a different issue.
> 
> Could you download the repo and use it as a shared project instead of having it through nuget.
> 
> Once you have done that, can you play around with it a bit see what exception is thrown?

Hi @LuckyDucko I actually have done that. I posted it here [Platform Not Supported on iOS Release](https://github.com/LuckyDucko/Mopups/issues/70)

**Comment by highwingers** [comment]
I am having exact same issue. ios is unable to compile using "REAL Device"
