### ISSUE TITLE
Repetitive clic on windows throws "No installed components were detected." 

### ISSUE THREAD

**Issue by jupagose** [LuckyDucko/Mopups#58]
I have a multiplatform project that uses Mopups, our first target for now is WINDOWS and let me say "MOPUPS" is greate tool.

But I'm having this issue, I use a MOPUP as a awaiting messsage it locks 

![image](https://user-images.githubusercontent.com/1399739/229369900-11ae65b9-cf77-484c-8f06-482ea172e6d6.png)

This popup is  started (PushAsync) before I start an API interaction, and is stoped (PopAsync) when that interaction finishes. My problem is when the user hits clic on one button several times while  a popup is opening.

Here is the stack trace 

   at WinRT.DelegateExtensions.DynamicInvokeAbi(Delegate del, Object[] invoke_params)
   at ABI.System.Collections.Generic.IVectorMethods`1.Append(IObjectReference obj, T value)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Mopups.Windows.Implementation.PopupPlatformWindows.<RemoveAsync>d__6.MoveNext()
   at Mopups.Services.PopupNavigation.<>c__DisplayClass23_0.<<RemovePageAsync>g__RemovePage|0>d.MoveNext()
   at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.<HandleSafeFireAndForget>d__16`1.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

Thaks for this great tool.

**Comment by LuckyDucko** [comment]
I use a lock for this normally. Here is the removepage async code here.

```csharp
public Task RemovePageAsync(PopupPage page, bool animate = true)
    {
        if (page == null)
            throw new InvalidOperationException("Page can not be null");

        if (!_popupStack.Contains(page))
            throw new InvalidOperationException("The page has not been pushed yet or has been removed already");

        return (MainThread.IsMainThread
            ? RemovePage()
            : MainThread.InvokeOnMainThreadAsync(RemovePage));


        async Task RemovePage()
        {
            lock (_locker)
            {
                if (!_popupStack.Contains(page))
                {
                    return;
                }
            }

            Popping?.Invoke(this, new PopupNavigationEventArgs(page, animate));
            await page.DisappearingAnimation();
            page.SendDisappearing();
            await PopupPlatform.RemoveAsync(page);
            page.DisposingAnimation();

            _popupStack.Remove(page);
            Popped?.Invoke(this, new PopupNavigationEventArgs(page, animate));
        }
    }
```

However, as i noticed you are using a loader, those can be quite the pain to make work properly.

here is the extension i made to the original rg.plugins.popup to help me out with making loaders, its not bullet proof however.
https://github.com/LuckyDucko/AwaitablePopups/blob/master/Services/PopupService.cs

You are correct about the async nature of these things. Can you provide a project for me that shows your problem (throw in a fake API that just uses Task.Delay or whatever) and i might be able to query up a solution for you.
