### ISSUE TITLE
Cannot Access A Disposed Object

### ISSUE THREAD

**Issue by raselldev** [LuckyDucko/Mopups#83]
Thank you for creating Mopups, 
Currently i got some error like this:

Terminating app due to uncaught exception 'System.ObjectDisposedException', reason: 'Cannot access a disposed object.
Object name: 'Mopups.Platforms.iOS.PopupWindow'. (System.ObjectDisposedException)
   at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException(Object o)
   at Foundation.NSObject.get_SuperHandle()
   at UIKit.UIView.get_Bounds()
   at BigTed.ProgressHUD.PositionHUD(NSNotification notification)
   at Foundation.InternalNSNotificationHandler.Post(NSNotification s)
   
   
   My shell using SimpleShell: https://github.com/RadekVyM
   
   Let me explain our flow, 
   
   1. User hit button on Mopups Page, the button contain code
   `try
    {
    Application.Current.MainPage = Handler.MauiContext.Services.GetRequiredService<FlyoutShell>();
    }
    catch(Exception ex)
    {
    System.Diagnostics.Debug.WriteLine(ex.Message);
    }`
    
    2. After this, user get MainPage 
    
    `
public FlyoutShell()
	{
        InitializeComponent();

        MopupService.Instance.PopAsync();
    }
    `

**Comment by raselldev** [comment]
Any updates for this issue? @LuckyDucko

**Comment by vatttsall** [comment]
Did you find any workaround?

**Comment by vecalion** [comment]
@raselldev @vatttsall did you figure out what is/was wrong? I'm facing the same issue in my project.

**Comment by doriangh** [comment]
@LuckyDucko I am experiencing the same issue. In my case, if I have a popup open, and I show a spinner (using Acr.UserDialogs), the app crashes when opening the keyboard with the following stacktrace:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Mopups.Platforms.iOS.PopupWindow'.
   at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException(Object o) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:line 52
   at Foundation.NSObject.get_SuperHandle() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 615
   at UIKit.UIView.get_Bounds() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIView.g.cs:line 3088
   at BigTed.ProgressHUD.PositionHUD(NSNotification notification)
   at Foundation.InternalNSNotificationHandler.Post(NSNotification s) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSNotificationCenter.cs:line 49
--- End of stack trace from previous location ---

**Comment by PrathamsGithub** [comment]
Any update on this? It is causing issue in some devices after adding the delay.

**Comment by Yabee-88** [comment]
I have the same error message after clicking TimePicker. Is there a solution

**Comment by andersonvieiragomeslopes** [comment]
Any updates or workaround?

**Comment by DigitApps2** [comment]
> Thank you for creating Mopups, Currently i got some error like this:
> 
> Terminating app due to uncaught exception 'System.ObjectDisposedException', reason: 'Cannot access a disposed object. Object name: 'Mopups.Platforms.iOS.PopupWindow'. (System.ObjectDisposedException) at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException(Object o) at Foundation.NSObject.get_SuperHandle() at UIKit.UIView.get_Bounds() at BigTed.ProgressHUD.PositionHUD(NSNotification notification) at Foundation.InternalNSNotificationHandler.Post(NSNotification s)
> 
> My shell using SimpleShell: https://github.com/RadekVyM
> 
> Let me explain our flow,
> 
> 1. User hit button on Mopups Page, the button contain code
>    `try     {     Application.Current.MainPage = Handler.MauiContext.Services.GetRequiredService<FlyoutShell>();     }     catch(Exception ex)     {     System.Diagnostics.Debug.WriteLine(ex.Message);     }`
> 
> ```
> 2. After this, user get MainPage 
> 
> `
> ```
> 
> public FlyoutShell() { InitializeComponent();
> 
> ```
>     MopupService.Instance.PopAsync();
> }
> `
> ```

Should be fixed in 2.2.1: https://www.nuget.org/packages/BTProgressHUD/2.2.1
